/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BreakMySupplyChainRouteImport } from './routes/break-my-supply-chain'
import { Route as CapabilityMapRouteImport } from './routes/capability-map'
import { Route as DisruptionsRouteImport } from './routes/disruptions'
import { Route as RecoveryPathsRouteImport } from './routes/recovery-paths'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as WorkforceRouteImport } from './routes/workforce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakMySupplyChainRoute = BreakMySupplyChainRouteImport.update({
  id: '/break-my-supply-chain',
  path: '/break-my-supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMapRoute = CapabilityMapRouteImport.update({
  id: '/capability-map',
  path: '/capability-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptionsRoute = DisruptionsRouteImport.update({
  id: '/disruptions',
  path: '/disruptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPathsRoute = RecoveryPathsRouteImport.update({
  id: '/recovery-paths',
  path: '/recovery-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/break-my-supply-chain': typeof BreakMySupplyChainRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/recovery-paths': typeof RecoveryPathsRoute
  '/resources': typeof ResourcesRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/break-my-supply-chain': typeof BreakMySupplyChainRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/recovery-paths': typeof RecoveryPathsRoute
  '/resources': typeof ResourcesRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/break-my-supply-chain': typeof BreakMySupplyChainRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/recovery-paths': typeof RecoveryPathsRoute
  '/resources': typeof ResourcesRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/break-my-supply-chain'
    | '/capability-map'
    | '/disruptions'
    | '/recovery-paths'
    | '/resources'
    | '/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/break-my-supply-chain'
    | '/capability-map'
    | '/disruptions'
    | '/recovery-paths'
    | '/resources'
    | '/workforce'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/break-my-supply-chain'
    | '/capability-map'
    | '/disruptions'
    | '/recovery-paths'
    | '/resources'
    | '/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BreakMySupplyChainRoute: typeof BreakMySupplyChainRoute
  CapabilityMapRoute: typeof CapabilityMapRoute
  DisruptionsRoute: typeof DisruptionsRoute
  RecoveryPathsRoute: typeof RecoveryPathsRoute
  ResourcesRoute: typeof ResourcesRoute
  WorkforceRoute: typeof WorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break-my-supply-chain': {
      id: '/break-my-supply-chain'
      path: '/break-my-supply-chain'
      fullPath: '/break-my-supply-chain'
      preLoaderRoute: typeof BreakMySupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-map': {
      id: '/capability-map'
      path: '/capability-map'
      fullPath: '/capability-map'
      preLoaderRoute: typeof CapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptions': {
      id: '/disruptions'
      path: '/disruptions'
      fullPath: '/disruptions'
      preLoaderRoute: typeof DisruptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-paths': {
      id: '/recovery-paths'
      path: '/recovery-paths'
      fullPath: '/recovery-paths'
      preLoaderRoute: typeof RecoveryPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BreakMySupplyChainRoute: BreakMySupplyChainRoute,
  CapabilityMapRoute: CapabilityMapRoute,
  DisruptionsRoute: DisruptionsRoute,
  RecoveryPathsRoute: RecoveryPathsRoute,
  ResourcesRoute: ResourcesRoute,
  WorkforceRoute: WorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
