/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilityMapRouteImport } from './routes/capability-map'
import { Route as DisruptionsRouteImport } from './routes/disruptions'
import { Route as ResourcesRouteImport } from './routes/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMapRoute = CapabilityMapRouteImport.update({
  id: '/capability-map',
  path: '/capability-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptionsRoute = DisruptionsRouteImport.update({
  id: '/disruptions',
  path: '/disruptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capability-map': typeof CapabilityMapRoute
  '/disruptions': typeof DisruptionsRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capability-map' | '/disruptions' | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capability-map' | '/disruptions' | '/resources'
  id: '__root__' | '/' | '/capability-map' | '/disruptions' | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilityMapRoute: typeof CapabilityMapRoute
  DisruptionsRoute: typeof DisruptionsRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-map': {
      id: '/capability-map'
      path: '/capability-map'
      fullPath: '/capability-map'
      preLoaderRoute: typeof CapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptions': {
      id: '/disruptions'
      path: '/disruptions'
      fullPath: '/disruptions'
      preLoaderRoute: typeof DisruptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilityMapRoute: CapabilityMapRoute,
  DisruptionsRoute: DisruptionsRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
